# Generated by Django 4.2.5 on 2023-09-09 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IHA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("agirlik", models.FloatField()),
                ("kategori", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Kiralama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField()),
                ("saat_araligi", models.CharField(max_length=100)),
                (
                    "iha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iha.iha"
                    ),
                ),
                (
                    "kiralayan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
