# Generated by Django 4.2.5 on 2023-09-09 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("iha", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kiralama",
            name="saat_araligi",
        ),
        migrations.AddField(
            model_name="kiralama",
            name="kiralama_baslangic_saati",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="kiralama",
            name="kiralama_bitis_saati",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
