# Generated by Django 4.2.5 on 2023-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iha", "0002_remove_kiralama_saat_araligi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kiralama",
            name="kiralama_baslangic_saati",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="kiralama",
            name="kiralama_bitis_saati",
            field=models.DateTimeField(),
        ),
    ]
