# Generated by Django 4.2.5 on 2023-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iha",
            "0004_rename_kiralama_baslangic_saati_kiralama_kiralama_baslangic_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="iha",
            name="kiralama_durumu",
            field=models.BooleanField(default=True),
        ),
    ]
