# Generated by Django 4.2.5 on 2023-09-10 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iha", "0006_alter_kiralama_iha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iha",
            name="kiralama_durumu",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="KiralamaGecmisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kiralama_baslangic", models.DateTimeField()),
                ("kiralama_bitis", models.DateTimeField()),
                ("iptal_edildi", models.BooleanField(default=False)),
                (
                    "iha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iha.iha"
                    ),
                ),
                (
                    "kiralayan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
