# Generated by Django 4.2.5 on 2023-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iha", "0007_alter_iha_kiralama_durumu_kiralamagecmisi"),
    ]

    operations = [
        migrations.AddField(
            model_name="kiralamagecmisi",
            name="gerceklesti",
            field=models.BooleanField(default=False),
        ),
    ]
